import { Abel } from "next/font/google";
import "./globals.css";
import "bootstrap/dist/css/bootstrap.min.css"

const inter = Abel({ subsets: ["latin"] , weight:"400" });

export const metadata = {
  title: "DEPI TASKS",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" >
      <body className={`${inter.className}`}>{children}</body>
    </html>
  );
}
